declare module 'lucide-react' {
  import * as React from 'react';
  export type Icon = React.FC<any>;
  export const Play: Icon;
  export const Pause: Icon;
  export const RotateCcw: Icon;
  export const FastForward: Icon;
  export const StepForward: Icon;
  export const Database: Icon;
  export const Cpu: Icon;
  export const CheckCircle: Icon;
  export const CheckCircle2: Icon;
  export const AlertCircle: Icon;
  export const AlertOctagon: Icon;
  export const AlertTriangle: Icon;
  export const ChevronRight: Icon;
  export const ChevronDown: Icon;
  export const Zap: Icon;
  export const Clock: Icon;
  export const Layers: Icon;
  export const Terminal: Icon;
  export const HelpCircle: Icon;
  export const ArrowRight: Icon;
  export const ArrowDown: Icon;
  export const ArrowUpDown: Icon;
  export const ShieldCheck: Icon;
  export const ShieldAlert: Icon;
  export const Split: Icon;
  export const Table: Icon;
  export const ListTree: Icon;
  export const GitCompare: Icon;
  export const GitBranch: Icon;
  export const GitFork: Icon;
  export const Activity: Icon;
  export const Sparkles: Icon;
  export const X: Icon;
  export const XCircle: Icon;
  export const ExternalLink: Icon;
  export const FileCode: Icon;
  export const FileText: Icon;
  export const Check: Icon;
  export const Info: Icon;
  export const BookOpen: Icon;
  export const Filter: Icon;
  export const Search: Icon;
  export const PlayCircle: Icon;
  export const Workflow: Icon;
  export const Eye: Icon;
  export const Scissors: Icon;
  export const MinusCircle: Icon;
  export const Minus: Icon;
  export const Binary: Icon;
  export const Hash: Icon;
  export const Code2: Icon;
  const anyExport: any;
  export default anyExport;
}
